#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: admin
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: postgres

#Server
SERVER_PORT: 8080
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: chatbotproject.hci@gmail.com
EMAIL_PASSWORD: bsgf lafh wblo qarz
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}