spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: admin
    username: postgres
  jpa:
    data-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_indetifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always
      continue-an-error: false
